# Generated by Django 5.2.12 on 2026-06-22

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(db_index=True, max_length=255, null=True)),
                (
                    "ref_name",
                    models.CharField(db_index=True, max_length=255, null=True),
                ),
                (
                    "ref_id",
                    models.CharField(db_index=True, max_length=255, null=True),
                ),
                (
                    "executed_at",
                    models.DateTimeField(auto_created=True, auto_now_add=True),
                ),
                (
                    "username",
                    models.CharField(db_index=True, max_length=255, null=True),
                ),
                (
                    "actor_role",
                    models.CharField(max_length=255, null=True),
                ),
                (
                    "actor_type",
                    models.CharField(
                        choices=[("User", "User"), ("System", "System")],
                        default="User",
                        max_length=20,
                    ),
                ),
                ("url", models.CharField(max_length=255, null=True)),
                (
                    "extra_informations",
                    models.JSONField(
                        blank=True,
                        null=True,
                        verbose_name="Extra information",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log",
                "verbose_name_plural": "Logs",
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["extra_informations"],
                        name="pg_audit_extra_info_gin",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DiffLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=25)),
                ("ref_name", models.CharField(db_index=True, max_length=255)),
                (
                    "ref_id",
                    models.CharField(db_index=True, max_length=255, null=True),
                ),
                ("column_name", models.CharField(db_index=True, max_length=255)),
                ("old_value", models.TextField(null=True)),
                ("new_value", models.TextField(null=True)),
                ("reason_for_change", models.TextField(blank=True, null=True)),
                (
                    "action_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pg_audit_models.actionlog",
                    ),
                ),
            ],
        ),
    ]
