# Generated by Django 5.2.12 on 2026-06-22

from django.db import migrations

CREATE_FUNCTION = """
    CREATE OR REPLACE FUNCTION fn_log_update()
    RETURNS TRIGGER AS
    $$
    DECLARE
        col RECORD;
        old_val TEXT;
        new_val TEXT;
        v_username TEXT;
        v_actor_type TEXT;
        v_actor_role TEXT;
        v_source TEXT;
        v_action_id BIGINT;
        v_action_log_exists BOOLEAN;
        v_ref_id TEXT;
        v_row_ref_id TEXT;
        v_pk_column TEXT;
        v_ref_name TEXT;
        v_url TEXT;
        v_extra_informations JSONB;
        v_reason_for_change_raw TEXT;
        v_reason_for_change_json JSONB;
        v_reason_for_change TEXT;
    BEGIN
        v_source := NULLIF(current_setting('app.source', true), '');
        v_username := NULLIF(current_setting('app.user', true), '');
        v_actor_type := COALESCE(NULLIF(current_setting('app.actor_type', true), ''), 'User');
        v_actor_role := NULLIF(current_setting('app.actor_role', true), '');
        v_action_id := NULLIF(current_setting('app.action_id', true), '')::INTEGER;
        v_ref_id := NULLIF(current_setting('app.ref_id', true), '');
        v_ref_name := NULLIF(current_setting('app.ref_name', true), '');
        v_url := NULLIF(current_setting('app.url', true), '');
        v_extra_informations := NULLIF(current_setting('app.extra_informations', true), '')::JSONB;
        v_reason_for_change_raw := NULLIF(current_setting('app.reason_for_change', true), '');

        IF v_action_id IS NOT NULL THEN
            SELECT EXISTS (
                SELECT 1
                FROM pg_audit_models_actionlog
                WHERE id = v_action_id
            )
            INTO v_action_log_exists;

            IF NOT v_action_log_exists THEN
                v_action_id := NULL;
                PERFORM set_config('app.action_id', '', false);
            END IF;
        END IF;

        SELECT a.attname
        INTO v_pk_column
        FROM pg_index i
        JOIN pg_attribute a
          ON a.attrelid = i.indrelid
         AND a.attnum = ANY(i.indkey)
        WHERE i.indrelid = TG_RELID
          AND i.indisprimary
        ORDER BY array_position(i.indkey, a.attnum)
        LIMIT 1;

        IF v_pk_column IS NOT NULL THEN
            IF TG_OP = 'DELETE' THEN
                EXECUTE format('SELECT ($1).%I::TEXT', v_pk_column)
                INTO v_row_ref_id
                USING OLD;
            ELSE
                EXECUTE format('SELECT ($1).%I::TEXT', v_pk_column)
                INTO v_row_ref_id
                USING NEW;
            END IF;
        END IF;

        IF v_ref_name IS NULL THEN
            v_ref_name := TG_TABLE_NAME;
        END IF;

        IF v_ref_name = TG_TABLE_NAME AND v_ref_id IS NULL THEN
            v_ref_id := v_row_ref_id;
        END IF;

        FOR col IN
            SELECT column_name
            FROM information_schema.columns
            WHERE table_name = TG_TABLE_NAME
            AND table_schema = TG_TABLE_SCHEMA
        LOOP
            IF TG_OP = 'INSERT' THEN
                EXECUTE format(
                    'SELECT NULL::TEXT, ($1).%I::TEXT',
                    col.column_name
                )
                INTO old_val, new_val
                USING NEW;
            ELSIF TG_OP = 'DELETE' THEN
                EXECUTE format(
                    'SELECT ($1).%I::TEXT, NULL::TEXT',
                    col.column_name
                )
                INTO old_val, new_val
                USING OLD;
            ELSE
                EXECUTE format(
                    'SELECT ($1).%I::TEXT, ($2).%I::TEXT',
                    col.column_name,
                    col.column_name
                )
                INTO old_val, new_val
                USING OLD, NEW;
            END IF;

            IF old_val IS DISTINCT FROM new_val THEN
                v_reason_for_change := v_reason_for_change_raw;

                IF v_reason_for_change_raw IS NOT NULL
                   AND LEFT(LTRIM(v_reason_for_change_raw), 1) = '{' THEN
                    BEGIN
                        v_reason_for_change_json := v_reason_for_change_raw::JSONB;
                        IF jsonb_typeof(v_reason_for_change_json) = 'object' THEN
                            v_reason_for_change := v_reason_for_change_json ->> col.column_name;
                        END IF;
                    EXCEPTION WHEN invalid_text_representation THEN
                        v_reason_for_change := v_reason_for_change_raw;
                    END;
                END IF;

                IF v_action_id IS NULL THEN
                    INSERT INTO pg_audit_models_actionlog (
                        source,
                        ref_id,
                        ref_name,
                        executed_at,
                        username,
                        actor_type,
                        actor_role,
                        url,
                        extra_informations
                    )
                    VALUES (
                        v_source,
                        v_ref_id,
                        v_ref_name,
                        NOW(),
                        v_username,
                        v_actor_type,
                        v_actor_role,
                        v_url,
                        v_extra_informations
                    )
                    RETURNING id INTO v_action_id;

                    PERFORM set_config('app.action_id', v_action_id::TEXT, false);
                END IF;

                INSERT INTO pg_audit_models_difflog (
                    action_log_id,
                    event_type,
                    ref_name,
                    ref_id,
                    column_name,
                    old_value,
                    new_value,
                    reason_for_change
                )
                VALUES (
                    v_action_id,
                    TG_OP,
                    TG_TABLE_NAME,
                    v_row_ref_id,
                    col.column_name,
                    old_val,
                    new_val,
                    v_reason_for_change
                );
            END IF;
        END LOOP;

        IF TG_OP = 'DELETE' THEN
            RETURN OLD;
        END IF;

        RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
"""

DROP_FUNCTION = """
    DROP FUNCTION IF EXISTS fn_log_update() CASCADE;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("pg_audit_models", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(CREATE_FUNCTION, DROP_FUNCTION),
    ]
