# Generated by Django 4.2.6 on 2025-09-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_audit_trail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestauditevent',
            name='request_body',
            field=models.TextField(blank=True, null=True, verbose_name='Request Body'),
        ),
        migrations.AddField(
            model_name='requestauditevent',
            name='response_body',
            field=models.TextField(blank=True, null=True, verbose_name='Response Body'),
        ),
    ]
