# Generated by Django 5.0.7 on 2025-10-10 19:52

import drf_audit_trail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drf_audit_trail", "0002_requestauditevent_request_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestauditevent",
            name="error_type",
            field=drf_audit_trail.fields.TruncatingCharField(
                blank=True, max_length=255, null=True, verbose_name="Error Type"
            ),
        ),
        migrations.AlterField(
            model_name="requestauditevent",
            name="query_params",
            field=drf_audit_trail.fields.TruncatingCharField(
                blank=True, max_length=2048, null=True, verbose_name="Query Parameters"
            ),
        ),
        migrations.AlterField(
            model_name="requestauditevent",
            name="url",
            field=drf_audit_trail.fields.TruncatingCharField(
                max_length=2048, verbose_name="URL"
            ),
        ),
    ]
