# Generated by Django 4.2.6 on 2026-03-13 19:19

from django.db import migrations
import drf_audit_trail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('drf_audit_trail', '0003_alter_requestauditevent_error_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestauditevent',
            name='user_agent',
            field=drf_audit_trail.fields.TruncatingCharField(blank=True, max_length=512, null=True, verbose_name='User Agent'),
        ),
    ]
