# Generated by Django 5.2.12 on 2026-05-05 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drf_audit_trail", "0004_requestauditevent_user_agent"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "extra_informations",
                    models.TextField(
                        blank=True, null=True, verbose_name="Extra information"
                    ),
                ),
                (
                    "datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="Datetime"),
                ),
                (
                    "actor_identifier",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=120,
                        null=True,
                        verbose_name="Actor identifier",
                    ),
                ),
                (
                    "actor_role",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="Actor role"
                    ),
                ),
                (
                    "actor_type",
                    models.CharField(
                        choices=[("User", "User"), ("System", "System")],
                        default="User",
                        max_length=20,
                        verbose_name="Actor type",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="Event type"
                    ),
                ),
                (
                    "action_description",
                    models.TextField(verbose_name="Action description"),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="Content type",
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        verbose_name="Object id",
                    ),
                ),
                (
                    "object_repr",
                    models.TextField(
                        blank=True, null=True, verbose_name="Object representation"
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Field name"
                    ),
                ),
                (
                    "old_values",
                    models.TextField(blank=True, null=True, verbose_name="Old values"),
                ),
                (
                    "new_values",
                    models.TextField(blank=True, null=True, verbose_name="New values"),
                ),
                (
                    "reason_for_change",
                    models.TextField(
                        blank=True, null=True, verbose_name="Reason for change"
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_log_entries",
                        to="drf_audit_trail.requestauditevent",
                        verbose_name="Request",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit log entry",
                "verbose_name_plural": "Audit log entries",
            },
        ),
    ]
