# Generated by Django 5.2.12 on 2026-09-01 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("drf_audit_trail", "0005_auditlogentry"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AuditLogEntry",
        ),
    ]
